{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "graylog.fullname" . }}-config
  labels:
    app: {{ template "graylog.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.config }}
{{- range $key, $value := .Values.config }}
  input_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "graylog.fullname" . }}-contentpack
  labels:
    app: {{ template "graylog.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.contentpack }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end -}}
