apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graylog.fullname" . }}
  labels:
    app: {{ template "graylog.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.passwordSecret }}
  password-secret: {{ .Values.passwordSecret | b64enc }}
  {{- else }}
  password-secret: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  {{- if .Values.rootPassword }}
  root-password-sha2: {{ .Values.rootPassword | b64enc }}
  {{- else }}
  root-password-sha2: {{ randAlphaNum 40 | b64enc }}
  {{- end }}
